### ISSUE TITLE
App Crash on Launch

### ISSUE THREAD

**Issue by mohdkhmais** [leftyio/hotjar#1]
I have this problem before the app starts. i have imported both 
dart_browser_loader + js. in yaml , flutter clean and run and still getting this
`
Compiler message:
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../hotjar/lib/src/hotjar_base.dart:5:8: Error: Not found: 'dart:html'
import "dart:html";
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:4:8: Error: Not found: 'dart:js'
import 'dart:js' as js;
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/utils.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:11:8: Error: Type 'ScriptElement' not found.
Future<ScriptElement> loadScript(
       ^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:10:8: Error: Type 'StyleElement' not found.
Future<StyleElement> loadInlineStyle(String style, {String id}) {
       ^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:28:8: Error: Type 'LinkElement' not found.
Future<LinkElement> loadLink(
       ^^^^^^^^^^^
../hotjar/lib/src/hotjar_base.dart:28:8: Error: Type 'ScriptElement' not found.
Future<ScriptElement> _loaded;
       ^^^^^^^^^^^^^
../hotjar/lib/src/hotjar_base.dart:41:8: Error: Type 'ScriptElement' not found.
Future<ScriptElement> loadHotjar(String siteId) =>
       ^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/utils.dart:4:5: Error: Type 'Element' not found.
Map<Element, Future> _mapper = {};
    ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/utils.dart:6:30: Error: Type 'Element' not found.
Future<T> waitLoad<T extends Element>(T element) {
                             ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:95:25: Error: Type 'HttpRequest' not found.
  void _openHttpRequest(HttpRequest request, String method, String url,
                        ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:30:25: Error: 'HttpRequest' isn't a type.
  final _xhrs = new Set<HttpRequest>();
                        ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:20:3: Error: 'ScriptElement' isn't a type.
  ScriptElement element = id != null
  ^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:21:9: Error: Getter not found: 'document'.
      ? document.getElementById(id)
        ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:22:9: Error: Getter not found: 'document'.
      : document.querySelector("script[src='$src']");
        ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:26:13: Error: Method not found: 'ScriptElement'.
  element = ScriptElement()
            ^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:44:3: Error: Getter not found: 'document'.
  document.head.append(element);
  ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/script.dart:53:6: Error: Getter not found: 'context'.
  js.context.callMethod("eval", [script]);
     ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:11:3: Error: 'StyleElement' isn't a type.
  StyleElement element = id != null ? document.getElementById(id) : null;
  ^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:11:39: Error: Getter not found: 'document'.
  StyleElement element = id != null ? document.getElementById(id) : null;
                                      ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:14:15: Error: Method not found: 'StyleElement'.
    element = StyleElement()..innerHtml = style;
              ^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:18:5: Error: Getter not found: 'document'.
    document.head.append(element);
    ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:34:3: Error: 'LinkElement' isn't a type.
  LinkElement element = id != null
  ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:35:9: Error: Getter not found: 'document'.
      ? document.getElementById(id)
        ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:36:9: Error: Getter not found: 'document'.
      : document.querySelector("link[href='$href']");
        ^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:39:15: Error: Method not found: 'LinkElement'.
    element = LinkElement()
              ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/style.dart:46:5: Error: Getter not found: 'document'.
    document.head.append(element);
    ^^^^^^^^
../hotjar/lib/src/hotjar_base.dart:28:8: Error: 'ScriptElement' isn't a type.
Future<ScriptElement> _loaded;
       ^^^^^^^^^^^^^
../hotjar/lib/src/hotjar_base.dart:35:15: Error: Method not found: 'loadInlineScript'.
  _loaded ??= loadInlineScript(_hJBaseScript, _scriptId);
              ^^^^^^^^^^^^^^^^
../hotjar/lib/src/hotjar_base.dart:42:5: Error: Method not found: 'loadInlineScript'.
    loadInlineScript(_hjScript(siteId), _scriptId);
    ^^^^^^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_browser_loader-0.0.6+1/lib/src/utils.dart:4:5: Error: 'Element' isn't a type.
Map<Element, Future> _mapper = {};
    ^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:44:19: Error: Method not found: 'HttpRequest'.
    var xhr = new HttpRequest();
                  ^^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:55:45: Error: Method not found: 'Blob'.
      var blob = xhr.response == null ? new Blob([]) : xhr.response;
                                            ^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:56:24: Error: Method not found: 'FileReader'.
      var reader = new FileReader();
                       ^^^^^^^^^^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+1/lib/src/browser_client.dart:95:25: Error: 'HttpRequest' isn't a type.
  void _openHttpRequest(HttpRequest request, String method, String url,
                        ^^^^^^^^^^^
../../../development/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:64:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved); // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
[38;5;248m#0      StandardFileSystem.entityForUri[39;49m
[38;5;248m#1      asFileUri  (package:vm/kernel_front_end.dart:604:37)[39;49m
[38;5;248m#2      writeDepfile  (package:vm/kernel_front_end.dart:799:21)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#3      FrontendCompiler.compile  (package:frontend_server/frontend_server.dart:472:15)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#4      _FlutterFrontendCompiler.compile  (package:flutter_frontend_server/server.dart:38:22)[39;49m
[38;5;248m#5      starter  (package:flutter_frontend_server/server.dart:149:27)[39;49m
[38;5;248m#6      main  (file:///b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)[39;49m
[38;5;244m#7      _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:32)[39;49m
[38;5;244m#8      _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/dev/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/dev/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 26s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
`

**Comment by mohdkhmais** [comment]
ITs-MacBook-Air:homiez-mobile dev$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-BH)
    • Flutter version 1.12.13+hotfix.8 at /Users/dev/development/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.9.0

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • ONEPLUS A6013 • eba6c535 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 2 categories.
ITs-MacBook-Air:homiez-mobile dev$

**Comment by lejard-h** [comment]
I've never use the package for Flutter Web.

Can give me more info about how you tried to use it ? How did you setup and run your app ?

From what I see in the log, you tried to use it in a non browser environment

**Comment by mohdkhmais** [comment]
@lejard-h here is the void main

```dart
void main()async{
  await loadScript("https://code.jquery.com/jquery-3.2.1.min.js");
  await loadLink("https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css");
  await loadInlineStyle('''
  body {
    color: red;
  }
  ''');
   loadHotjar("mySiteIDhere");
   hj("trigger", "my-poll");
   hj("tagRecording",  ["tag1", "tag2"]);
  runApp(MyApp());
}
```

**Comment by lejard-h** [comment]
Are you running the app with the following command ? `flutter run -d chrome`

**Comment by mohdkhmais** [comment]
@lejard-h no i am running this with my mobile Android oneplus 6t

**Comment by lejard-h** [comment]
[Hotjar](www.hotjar.com) is for web app only therefore the package should be compatible with Flutter on the web not on mobile.

Same with `dart_browser_loader`, it's a browser package. You can't load Javascript or Css inside an Android or iOS app.

**Comment by mohdkhmais** [comment]
@lejard-h aha ok my bad sorry

**Comment by lejard-h** [comment]
@mohdkhmais No worries :) 
If you need analytics on you mobile app you can try https://pub.dev/packages/firebase_analytics
and https://pub.dev/packages/sentry if you need crash reporting
